-file("/usr/local/lib/erlang/lib/parsetools-2.1/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(ex_graphql_lexer).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("src/ex_graphql_lexer.xrl", 58).

-file("/usr/local/lib/erlang/lib/parsetools-2.1/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transistion state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,_Tlen,_Ics1,_L1,_S1} ->
            string_cont(yysuf(Tcs, Alen), L0, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

-dialyzer({nowarn_function, string_cont/4}).

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,_Tlen1,_Ics1,_L1,_S1} ->       % Use last accept match
            token_cont(yysuf(Tcs, Alen1), L0, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

-dialyzer({nowarn_function, token_cont/3}).

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,_L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            tokens_cont(yysuf(Tcs, Alen1), L0, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

-dialyzer({nowarn_function, tokens_cont/4}).

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            skip_cont(yysuf(Tcs, Alen1), L1, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

-dialyzer({nowarn_function, skip_cont/4}).

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("src/ex_graphql_lexer.erl", 284).
yystate() -> 53.

yystate(84, [117|Ics], Line, Tlen, Action, Alen) ->
    yystate(43, Ics, Line, Tlen+1, Action, Alen);
yystate(84, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(84, [115|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(84, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(84, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(84, [102|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(84, [98|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(84, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(84, Ics, Line, Tlen+1, Action, Alen);
yystate(84, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(84, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(84, [11|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(84, [12|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(84, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(84, [C|Ics], Line, Tlen, Action, Alen) when C >= 14, C =< 33 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(84, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 46 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(84, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 91 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(84, [C|Ics], Line, Tlen, Action, Alen) when C >= 93, C =< 97 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(84, [C|Ics], Line, Tlen, Action, Alen) when C >= 99, C =< 101 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(84, [C|Ics], Line, Tlen, Action, Alen) when C >= 103, C =< 109 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(84, [C|Ics], Line, Tlen, Action, Alen) when C >= 111, C =< 113 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(84, [C|Ics], Line, Tlen, Action, Alen) when C >= 118, C =< 8231 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(84, [C|Ics], Line, Tlen, Action, Alen) when C >= 8234 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(84, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,84};
yystate(83, [110|Ics], Line, Tlen, _, _) ->
    yystate(14, Ics, Line, Tlen+1, 7, Tlen);
yystate(83, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(83, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,83};
yystate(82, [97|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 7, Tlen);
yystate(82, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(82, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,82};
yystate(81, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(81, Ics, Line, Tlen+1, 4, Tlen);
yystate(81, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,81};
yystate(80, [101|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 7, Tlen);
yystate(80, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(80, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,80};
yystate(79, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(79, [C|Ics], Line, Tlen, Action, Alen) when C >= 49, C =< 57 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(79, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,79};
yystate(78, [101|Ics], Line, Tlen, _, _) ->
    yystate(68, Ics, Line, Tlen+1, 7, Tlen);
yystate(78, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(78, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,78};
yystate(77, [101|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 7, Tlen);
yystate(77, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(77, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,77};
yystate(76, [114|Ics], Line, Tlen, _, _) ->
    yystate(44, Ics, Line, Tlen+1, 7, Tlen);
yystate(76, [97|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 7, Tlen);
yystate(76, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(76, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(76, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(76, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 113 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(76, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(76, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,76};
yystate(75, [117|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line, Tlen+1, 7, Tlen);
yystate(75, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(75, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,75};
yystate(74, [116|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 7, Tlen);
yystate(74, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(74, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,74};
yystate(73, [122|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(73, [121|Ics], Line, Tlen, _, _) ->
    yystate(68, Ics, Line, Tlen+1, 7, Tlen);
yystate(73, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 120 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(73, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,73};
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(72, Ics, Line, Tlen+1, 4, Tlen);
yystate(72, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,72};
yystate(71, [116|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 7, Tlen);
yystate(71, [112|Ics], Line, Tlen, _, _) ->
    yystate(46, Ics, Line, Tlen+1, 7, Tlen);
yystate(71, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 111 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 113, C =< 115 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(71, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,71};
yystate(70, [110|Ics], Line, Tlen, _, _) ->
    yystate(68, Ics, Line, Tlen+1, 7, Tlen);
yystate(70, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(70, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,70};
yystate(69, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line};
yystate(68, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 2, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 2, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 2, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 2, Tlen);
yystate(68, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,68};
yystate(67, [101|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 7, Tlen);
yystate(67, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(67, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,67};
yystate(66, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(66, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(66, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(66, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,66};
yystate(65, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(81, Ics, Line, Tlen+1, Action, Alen);
yystate(65, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,65};
yystate(64, [97|Ics], Line, Tlen, _, _) ->
    yystate(32, Ics, Line, Tlen+1, 7, Tlen);
yystate(64, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(64, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,64};
yystate(63, [101|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 7, Tlen);
yystate(63, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(63, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,63};
yystate(62, [115|Ics], Line, Tlen, _, _) ->
    yystate(68, Ics, Line, Tlen+1, 7, Tlen);
yystate(62, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(62, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,62};
yystate(61, [109|Ics], Line, Tlen, _, _) ->
    yystate(29, Ics, Line, Tlen+1, 7, Tlen);
yystate(61, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 108 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 110, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(61, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,61};
yystate(60, [99|Ics], Line, Tlen, _, _) ->
    yystate(78, Ics, Line, Tlen+1, 7, Tlen);
yystate(60, [97|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(60, [98|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(60, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(60, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,60};
yystate(59, [11|Ics], Line, Tlen, _, _) ->
    yystate(59, Ics, Line, Tlen+1, 0, Tlen);
yystate(59, [12|Ics], Line, Tlen, _, _) ->
    yystate(59, Ics, Line, Tlen+1, 0, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(59, Ics, Line, Tlen+1, 0, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 14, C =< 8231 ->
    yystate(59, Ics, Line, Tlen+1, 0, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 8234 ->
    yystate(59, Ics, Line, Tlen+1, 0, Tlen);
yystate(59, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,59};
yystate(58, [110|Ics], Line, Tlen, _, _) ->
    yystate(26, Ics, Line, Tlen+1, 7, Tlen);
yystate(58, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(58, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,58};
yystate(57, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(81, Ics, Line, Tlen+1, Action, Alen);
yystate(57, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,57};
yystate(56, [108|Ics], Line, Tlen, _, _) ->
    yystate(82, Ics, Line, Tlen+1, 7, Tlen);
yystate(56, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(56, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,56};
yystate(55, [110|Ics], Line, Tlen, _, _) ->
    yystate(71, Ics, Line, Tlen+1, 7, Tlen);
yystate(55, [109|Ics], Line, Tlen, _, _) ->
    yystate(13, Ics, Line, Tlen+1, 7, Tlen);
yystate(55, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 108 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(55, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,55};
yystate(54, [92|Ics], Line, Tlen, _, _) ->
    yystate(84, Ics, Line, Tlen+1, 5, Tlen);
yystate(54, [34|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 5, Tlen);
yystate(54, [11|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 5, Tlen);
yystate(54, [12|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 5, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(5, Ics, Line, Tlen+1, 5, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 14, C =< 33 ->
    yystate(5, Ics, Line, Tlen+1, 5, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 91 ->
    yystate(5, Ics, Line, Tlen+1, 5, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 93, C =< 8231 ->
    yystate(5, Ics, Line, Tlen+1, 5, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 8234 ->
    yystate(5, Ics, Line, Tlen+1, 5, Tlen);
yystate(54, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,54};
yystate(53, [8232|Ics], Line, Tlen, Action, Alen) ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [8233|Ics], Line, Tlen, Action, Alen) ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [160|Ics], Line, Tlen, Action, Alen) ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [117|Ics], Line, Tlen, Action, Alen) ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(4, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [115|Ics], Line, Tlen, Action, Alen) ->
    yystate(7, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [113|Ics], Line, Tlen, Action, Alen) ->
    yystate(18, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [112|Ics], Line, Tlen, Action, Alen) ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [109|Ics], Line, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [105|Ics], Line, Tlen, Action, Alen) ->
    yystate(55, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [103|Ics], Line, Tlen, Action, Alen) ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [104|Ics], Line, Tlen, Action, Alen) ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [102|Ics], Line, Tlen, Action, Alen) ->
    yystate(76, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [64|Ics], Line, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(79, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [40|Ics], Line, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [41|Ics], Line, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [36|Ics], Line, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(59, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [13|Ics], Line, Tlen, Action, Alen) ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [11|Ics], Line, Tlen, Action, Alen) ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [12|Ics], Line, Tlen, Action, Alen) ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(69, Ics, Line+1, Tlen+1, Action, Alen);
yystate(53, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(69, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [C|Ics], Line, Tlen, Action, Alen) when C >= 49, C =< 57 ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 100 ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [C|Ics], Line, Tlen, Action, Alen) when C >= 106, C =< 108 ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [C|Ics], Line, Tlen, Action, Alen) when C >= 118, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, Action, Alen);
yystate(53, [C|Ics], Line, Tlen, Action, Alen) when C >= 123, C =< 125 ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(53, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,53};
yystate(52, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(84, Ics, Line, Tlen+1, Action, Alen);
yystate(52, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(52, [11|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(52, [12|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(52, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(52, [C|Ics], Line, Tlen, Action, Alen) when C >= 14, C =< 33 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(52, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 47 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(52, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(52, [C|Ics], Line, Tlen, Action, Alen) when C >= 58, C =< 64 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(52, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(52, [C|Ics], Line, Tlen, Action, Alen) when C >= 71, C =< 91 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(52, [C|Ics], Line, Tlen, Action, Alen) when C >= 93, C =< 96 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(52, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(52, [C|Ics], Line, Tlen, Action, Alen) when C >= 103, C =< 8231 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(52, [C|Ics], Line, Tlen, Action, Alen) when C >= 8234 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(52, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,52};
yystate(51, [101|Ics], Line, Tlen, _, _) ->
    yystate(83, Ics, Line, Tlen+1, 7, Tlen);
yystate(51, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(51, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,51};
yystate(50, [114|Ics], Line, Tlen, _, _) ->
    yystate(68, Ics, Line, Tlen+1, 7, Tlen);
yystate(50, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(50, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,50};
yystate(49, [117|Ics], Line, Tlen, _, _) ->
    yystate(17, Ics, Line, Tlen+1, 7, Tlen);
yystate(49, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(49, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,49};
yystate(48, [116|Ics], Line, Tlen, _, _) ->
    yystate(80, Ics, Line, Tlen+1, 7, Tlen);
yystate(48, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(48, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,48};
yystate(47, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(47, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,47};
yystate(46, [117|Ics], Line, Tlen, _, _) ->
    yystate(14, Ics, Line, Tlen+1, 7, Tlen);
yystate(46, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(46, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,46};
yystate(45, [108|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 7, Tlen);
yystate(45, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(45, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(45, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,45};
yystate(44, [97|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 7, Tlen);
yystate(44, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(44, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,44};
yystate(43, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(84, Ics, Line, Tlen+1, Action, Alen);
yystate(43, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(43, [11|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(43, [12|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(43, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(43, [C|Ics], Line, Tlen, Action, Alen) when C >= 14, C =< 33 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(43, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 47 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(43, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(11, Ics, Line, Tlen+1, Action, Alen);
yystate(43, [C|Ics], Line, Tlen, Action, Alen) when C >= 58, C =< 64 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(43, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(11, Ics, Line, Tlen+1, Action, Alen);
yystate(43, [C|Ics], Line, Tlen, Action, Alen) when C >= 71, C =< 91 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(43, [C|Ics], Line, Tlen, Action, Alen) when C >= 93, C =< 96 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(43, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(11, Ics, Line, Tlen+1, Action, Alen);
yystate(43, [C|Ics], Line, Tlen, Action, Alen) when C >= 103, C =< 8231 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(43, [C|Ics], Line, Tlen, Action, Alen) when C >= 8234 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(43, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,43};
yystate(42, [117|Ics], Line, Tlen, _, _) ->
    yystate(74, Ics, Line, Tlen+1, 7, Tlen);
yystate(42, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(42, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,42};
yystate(41, [114|Ics], Line, Tlen, _, _) ->
    yystate(73, Ics, Line, Tlen+1, 7, Tlen);
yystate(41, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(41, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,41};
yystate(40, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(40, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,40};
yystate(39, [108|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 7, Tlen);
yystate(39, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(39, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,39};
yystate(38, [111|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 7, Tlen);
yystate(38, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(38, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,38};
yystate(37, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line};
yystate(36, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(36, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,36};
yystate(35, [114|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 7, Tlen);
yystate(35, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(35, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,35};
yystate(34, [101|Ics], Line, Tlen, _, _) ->
    yystate(66, Ics, Line, Tlen+1, 4, Tlen);
yystate(34, [69|Ics], Line, Tlen, _, _) ->
    yystate(66, Ics, Line, Tlen+1, 4, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(34, Ics, Line, Tlen+1, 4, Tlen);
yystate(34, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,34};
yystate(33, [109|Ics], Line, Tlen, _, _) ->
    yystate(68, Ics, Line, Tlen+1, 7, Tlen);
yystate(33, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 108 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 110, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(33, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,33};
yystate(32, [116|Ics], Line, Tlen, _, _) ->
    yystate(0, Ics, Line, Tlen+1, 7, Tlen);
yystate(32, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(32, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,32};
yystate(31, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 6, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 6, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 6, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 6, Tlen);
yystate(31, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,31};
yystate(30, [116|Ics], Line, Tlen, _, _) ->
    yystate(62, Ics, Line, Tlen+1, 7, Tlen);
yystate(30, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(30, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,30};
yystate(29, [101|Ics], Line, Tlen, _, _) ->
    yystate(2, Ics, Line, Tlen+1, 7, Tlen);
yystate(29, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(29, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,29};
yystate(28, [97|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 7, Tlen);
yystate(28, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(28, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,28};
yystate(27, [112|Ics], Line, Tlen, _, _) ->
    yystate(78, Ics, Line, Tlen+1, 7, Tlen);
yystate(27, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 111 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 113, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(27, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,27};
yystate(26, [100|Ics], Line, Tlen, _, _) ->
    yystate(68, Ics, Line, Tlen+1, 7, Tlen);
yystate(26, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(26, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(26, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,26};
yystate(25, [101|Ics], Line, Tlen, _, _) ->
    yystate(65, Ics, Line, Tlen+1, 3, Tlen);
yystate(25, [69|Ics], Line, Tlen, _, _) ->
    yystate(65, Ics, Line, Tlen+1, 3, Tlen);
yystate(25, [46|Ics], Line, Tlen, _, _) ->
    yystate(6, Ics, Line, Tlen+1, 3, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(25, Ics, Line, Tlen+1, 3, Tlen);
yystate(25, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,25};
yystate(24, [97|Ics], Line, Tlen, _, _) ->
    yystate(56, Ics, Line, Tlen+1, 7, Tlen);
yystate(24, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(24, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,24};
yystate(23, [115|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line, Tlen+1, 7, Tlen);
yystate(23, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(23, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,23};
yystate(22, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line};
yystate(21, [110|Ics], Line, Tlen, _, _) ->
    yystate(0, Ics, Line, Tlen+1, 7, Tlen);
yystate(21, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(21, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,21};
yystate(20, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(84, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [11|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [12|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [C|Ics], Line, Tlen, Action, Alen) when C >= 14, C =< 33 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 47 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [C|Ics], Line, Tlen, Action, Alen) when C >= 58, C =< 64 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [C|Ics], Line, Tlen, Action, Alen) when C >= 71, C =< 91 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [C|Ics], Line, Tlen, Action, Alen) when C >= 93, C =< 96 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [C|Ics], Line, Tlen, Action, Alen) when C >= 103, C =< 8231 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(20, [C|Ics], Line, Tlen, Action, Alen) when C >= 8234 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(20, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,20};
yystate(19, [109|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 7, Tlen);
yystate(19, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 108 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 110, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(19, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,19};
yystate(18, [117|Ics], Line, Tlen, _, _) ->
    yystate(9, Ics, Line, Tlen+1, 7, Tlen);
yystate(18, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(18, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,18};
yystate(17, [108|Ics], Line, Tlen, _, _) ->
    yystate(10, Ics, Line, Tlen+1, 7, Tlen);
yystate(17, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(17, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,17};
yystate(16, [121|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(16, [122|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(16, [120|Ics], Line, Tlen, _, _) ->
    yystate(48, Ics, Line, Tlen+1, 7, Tlen);
yystate(16, [110|Ics], Line, Tlen, _, _) ->
    yystate(1, Ics, Line, Tlen+1, 7, Tlen);
yystate(16, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 119 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(16, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,16};
yystate(15, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(15, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,15};
yystate(14, [116|Ics], Line, Tlen, _, _) ->
    yystate(68, Ics, Line, Tlen+1, 7, Tlen);
yystate(14, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(14, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(14, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,14};
yystate(13, [112|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 7, Tlen);
yystate(13, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 111 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 113, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(13, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,13};
yystate(12, [103|Ics], Line, Tlen, _, _) ->
    yystate(19, Ics, Line, Tlen+1, 7, Tlen);
yystate(12, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 104, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(12, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,12};
yystate(11, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(84, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [11|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [12|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [C|Ics], Line, Tlen, Action, Alen) when C >= 14, C =< 33 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 47 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [C|Ics], Line, Tlen, Action, Alen) when C >= 58, C =< 64 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [C|Ics], Line, Tlen, Action, Alen) when C >= 71, C =< 91 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [C|Ics], Line, Tlen, Action, Alen) when C >= 93, C =< 96 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [C|Ics], Line, Tlen, Action, Alen) when C >= 103, C =< 8231 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(11, [C|Ics], Line, Tlen, Action, Alen) when C >= 8234 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(11, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,11};
yystate(10, [108|Ics], Line, Tlen, _, _) ->
    yystate(68, Ics, Line, Tlen+1, 7, Tlen);
yystate(10, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(10, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(10, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,10};
yystate(9, [101|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 7, Tlen);
yystate(9, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(9, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,9};
yystate(8, [101|Ics], Line, Tlen, _, _) ->
    yystate(65, Ics, Line, Tlen+1, 3, Tlen);
yystate(8, [69|Ics], Line, Tlen, _, _) ->
    yystate(65, Ics, Line, Tlen+1, 3, Tlen);
yystate(8, [46|Ics], Line, Tlen, _, _) ->
    yystate(6, Ics, Line, Tlen+1, 3, Tlen);
yystate(8, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,8};
yystate(7, [99|Ics], Line, Tlen, _, _) ->
    yystate(24, Ics, Line, Tlen+1, 7, Tlen);
yystate(7, [97|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(7, [98|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(7, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(7, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,7};
yystate(6, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(6, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,6};
yystate(5, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(84, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [11|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [12|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [C|Ics], Line, Tlen, Action, Alen) when C >= 14, C =< 33 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [C|Ics], Line, Tlen, Action, Alen) when C >= 93, C =< 8231 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(5, [C|Ics], Line, Tlen, Action, Alen) when C >= 8234 ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(5, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,5};
yystate(4, [122|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(4, [121|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 7, Tlen);
yystate(4, [114|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 7, Tlen);
yystate(4, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 120 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(4, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,4};
yystate(3, [102|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 7, Tlen);
yystate(3, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 101 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 103, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(3, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,3};
yystate(2, [110|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 7, Tlen);
yystate(2, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(2, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,2};
yystate(1, [117|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 7, Tlen);
yystate(1, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(1, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,1};
yystate(0, [105|Ics], Line, Tlen, _, _) ->
    yystate(38, Ics, Line, Tlen+1, 7, Tlen);
yystate(0, [95|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(36, Ics, Line, Tlen+1, 7, Tlen);
yystate(0, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,0};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, _, _, _) ->
    yyaction_0();
yyaction(1, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_1(TokenChars, TokenLine);
yyaction(2, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_2(TokenChars, TokenLine);
yyaction(3, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_3(TokenChars, TokenLine);
yyaction(4, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_4(TokenChars, TokenLine);
yyaction(5, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_5(TokenChars, TokenLine);
yyaction(6, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_6(TokenChars, TokenLine);
yyaction(7, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_7(TokenChars, TokenLine);
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/0}).
-file("src/ex_graphql_lexer.xrl", 47).
yyaction_0() ->
     skip_token .

-compile({inline,yyaction_1/2}).
-file("src/ex_graphql_lexer.xrl", 48).
yyaction_1(TokenChars, TokenLine) ->
     { token, { list_to_atom (TokenChars), TokenLine } } .

-compile({inline,yyaction_2/2}).
-file("src/ex_graphql_lexer.xrl", 49).
yyaction_2(TokenChars, TokenLine) ->
     { token, { list_to_atom (TokenChars), TokenLine } } .

-compile({inline,yyaction_3/2}).
-file("src/ex_graphql_lexer.xrl", 50).
yyaction_3(TokenChars, TokenLine) ->
     { token, { int_value, TokenLine, TokenChars } } .

-compile({inline,yyaction_4/2}).
-file("src/ex_graphql_lexer.xrl", 51).
yyaction_4(TokenChars, TokenLine) ->
     { token, { float_value, TokenLine, TokenChars } } .

-compile({inline,yyaction_5/2}).
-file("src/ex_graphql_lexer.xrl", 52).
yyaction_5(TokenChars, TokenLine) ->
     { token, { string_value, TokenLine, TokenChars } } .

-compile({inline,yyaction_6/2}).
-file("src/ex_graphql_lexer.xrl", 53).
yyaction_6(TokenChars, TokenLine) ->
     { token, { boolean_value, TokenLine, TokenChars } } .

-compile({inline,yyaction_7/2}).
-file("src/ex_graphql_lexer.xrl", 54).
yyaction_7(TokenChars, TokenLine) ->
     { token, { name, TokenLine, TokenChars } } .

-file("/usr/local/lib/erlang/lib/parsetools-2.1/include/leexinc.hrl", 290).
